/*
Show Pratoomratana - CS2263 - HW1
V1.0.0
This Java source file was generated by the Gradle 'init' task.
*/
package edu.isu.cs2263.hw01;
//Gradle was not happy compiling without these for some reason.
import org.apache.commons.cli.CommandLine;
import org.apache.commons.cli.CommandLineParser;
import org.apache.commons.cli.DefaultParser;
import org.apache.commons.cli.Options;
import org.apache.commons.cli.ParseException;

public class App {
    // Output for the help command
    private void help(){
      System.out.println("usage: Calc [OPTIONS]\nEvaluation of simple mathematical expressions\n-b,--batch <file>    batch file containing expressions to evaluate\n-h,--help            print usage message\n-o,--output <file>   output file:");
    }
    //batch and output just copy the next argument, it does not check if it's a file.
    private void batch(String[] args){
      System.out.println("Batch value: " + args[1]);
    }
    private void output(String[] args){
      System.out.println("Batch value: " + args[1]);
    }

    public static void main(String[] args) throws ParseException{
      //Main class object
      App app = new App();
      //Options objects for -h, -b and -o
      Options options = new Options();
      options.addOption("h", "help", false, "displays list of commands");
      options.addOption("b", "batch", false, "processes the provided file");
      options.addOption("o", "output", false, "sends the output to the provided file and standard output");

      //Parcser for delimiting the string from the command line.
      CommandLineParser parser = new DefaultParser();
      CommandLine cmd = parser.parse(options, args);
      //No argument, displays unique help message
      String tooManyArg = "Too many arguments please provide a single file name.";
      if(args.length <= 0){
        System.out.println("No argument provided. \nUsage gradle run --args='[Argument]'\nE.G: gradle run --args='-h' for a list of arguments");
      }
      else if(cmd.hasOption("h")){
        app.help();
      }
      //Simply passing the array of strings and using index 1(provided file.)
      else if(cmd.hasOption("b")){
        //Minor error catching
        if (args.length >= 3){
          System.out.println(tooManyArg);
        }
        app.batch(args);
      }
      else if(cmd.hasOption("o")){
        if (args.length >= 3){
          System.out.println(tooManyArg);
        }
        app.output(args);
      }
    }
}
